### ISSUE TITLE
Attempted install brakes the domain scripts

### ISSUE THREAD

**Issue by WagnerBeccard** [custom-components/custom_updater#100]
## Describe the bug

Attempted the install of the component. Set up the configuration and parts of lovelace. 
then hit restart. 
Scripts stopped working and still try to get it back working - No other chanages where made. 
hit another restart, deleted all configuration and files then, 
Still cant use scripts. 

## `custom_updater` configuration

```yaml

none

```

## Resources in lovelace configuration

```yaml

resources:
  - type: js
    url: /local/customcards/kiosk.js?v=0.1
  - type: module
    url: /local/customcards/useful-markdown-card.js
  - type: js
    url: /local/customcards/card-tools.js?v=0.31
  - type: js
    url: /local/customcards/card-modder.js?v=1.1
  - type: js
    url: /local/customcards/layout-card.js?v=1

```

## Tracker-card configuration

```yaml

none
```

## Debug log

```
019-02-25 16:58:13 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 56, in async_setup_component
    return await task  # type: ignore
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 124, in _async_setup_component
    conf_util.async_process_component_config(hass, config, domain)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/config.py", line 711, in async_process_component_config
    config = component.CONFIG_SCHEMA(config)  # type: ignore
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 381, in validate_mapping
    cval = cvalue(key_path, value)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 811, in validate_callable
    return schema(data)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/config_validation.py", line 390, in verify
    return schema(value)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 381, in validate_mapping
    cval = cvalue(key_path, value)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 811, in validate_callable
    return schema(data)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 381, in validate_mapping
    cval = cvalue(key_path, value)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/validators.py", line 204, in _run
    return self._exec(self._compiled, value, path)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/validators.py", line 284, in _exec
    v = func(path, v)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 630, in validate_sequence
    cval = validate(index_path, value)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/validators.py", line 204, in _run
    return self._exec(self._compiled, value, path)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/validators.py", line 249, in _exec
    return func(path, v)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/validators.py", line 204, in _run
    return self._exec(self._compiled, value, path)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/validators.py", line 284, in _exec
    v = func(path, v)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 811, in validate_callable
    return schema(data)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 381, in validate_mapping
    cval = cvalue(key_path, value)
  File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 811, in validate_callable
    return schema(data)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/config_validation.py", line 354, in service
    if valid_entity_id(value):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 80, in valid_entity_id
    return ('.' in entity_id and
TypeError: argument of type 'NoneType' is not iterable
```

Trying to resolfe this in the venv
```
homeassistant@MACBOOKPRO:/srv$ pip install pyupdate==1.3.1
Collecting pyupdate==1.3.1
  Downloading https://files.pythonhosted.org/packages/f5/c6/f172b891740fc3801ab609391f8aede9e2503fe823a33fac28c7de91580b/pyupdate-1.3.1.tar.gz
Collecting requests (from pyupdate==1.3.1)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests->pyupdate==1.3.1)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->pyupdate==1.3.1)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->pyupdate==1.3.1)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests->pyupdate==1.3.1)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Building wheels for collected packages: pyupdate
  Running setup.py bdist_wheel for pyupdate ... done
  Stored in directory: /home/homeassistant/.cache/pip/wheels/bf/bc/6e/0639b74e81a146dd37aa98e2e10df5ad481ed4035e5438987a
Successfully built pyupdate
Installing collected packages: urllib3, certifi, chardet, idna, requests, pyupdate
Successfully installed certifi-2018.11.29 chardet-3.0.4 idna-2.8 pyupdate-1.3.1 requests-2.21.0 urllib3-1.24.1
homeassistant@MACBOOKPRO:/srv$ pip3 install  pyupdate==1.3.1
Collecting pyupdate==1.3.1
  Using cached https://files.pythonhosted.org/packages/f5/c6/f172b891740fc3801ab609391f8aede9e2503fe823a33fac28c7de91580b/pyupdate-1.3.1.tar.gz
Collecting requests (from pyupdate==1.3.1)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->pyupdate==1.3.1)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->pyupdate==1.3.1)
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests->pyupdate==1.3.1)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests->pyupdate==1.3.1)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Building wheels for collected packages: pyupdate
  Running setup.py bdist_wheel for pyupdate ... done
  Stored in directory: /home/homeassistant/.cache/pip/wheels/bf/bc/6e/0639b74e81a146dd37aa98e2e10df5ad481ed4035e5438987a
Successfully built pyupdate
Installing collected packages: chardet, certifi, urllib3, idna, requests, pyupdate
Successfully installed certifi-2018.11.29 chardet-3.0.4 idna-2.8 pyupdate-1.3.1 requests-2.21.0 urllib3-1.24.1

```

**Comment by ludeeus** [comment]
your pip command is wrong, you have `install` two times

**Comment by WagnerBeccard** [comment]
dang, edited - Does'nt bring back the script domain

**Comment by ludeeus** [comment]
This has nothing to do with scripts... so that is strange....
What errors do you get?

**Comment by WagnerBeccard** [comment]
Only the ```

Feb 25 17:55:47 MACBOOKPRO hass[22938]:     return func(path, v)
Feb 25 17:55:47 MACBOOKPRO hass[22938]:   File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/validators.py", line 204, in _run
Feb 25 17:55:47 MACBOOKPRO hass[22938]:     return self._exec(self._compiled, value, path)
Feb 25 17:55:47 MACBOOKPRO hass[22938]:   File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/validators.py", line 284, in _exec
Feb 25 17:55:47 MACBOOKPRO hass[22938]:     v = func(path, v)
Feb 25 17:55:47 MACBOOKPRO hass[22938]:   File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 811, in validate_callable
Feb 25 17:55:47 MACBOOKPRO hass[22938]:     return schema(data)
Feb 25 17:55:47 MACBOOKPRO hass[22938]:   File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 267, in __call__
Feb 25 17:55:47 MACBOOKPRO hass[22938]:     return self._compiled([], data)
Feb 25 17:55:47 MACBOOKPRO hass[22938]:   File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
Feb 25 17:55:47 MACBOOKPRO hass[22938]:     return base_validate(path, iteritems(data), out)
Feb 25 17:55:47 MACBOOKPRO hass[22938]:   File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 381, in validate_mapping
Feb 25 17:55:47 MACBOOKPRO hass[22938]:     cval = cvalue(key_path, value)
Feb 25 17:55:47 MACBOOKPRO hass[22938]:   File "/srv/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 811, in validate_callable
Feb 25 17:55:47 MACBOOKPRO hass[22938]:     return schema(data)
Feb 25 17:55:47 MACBOOKPRO hass[22938]:   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/config_validation.py", line 354, in service
Feb 25 17:55:47 MACBOOKPRO hass[22938]:     if valid_entity_id(value):
Feb 25 17:55:47 MACBOOKPRO hass[22938]:   File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 80, in valid_entity_id
Feb 25 17:55:47 MACBOOKPRO hass[22938]:     return ('.' in entity_id and
Feb 25 17:55:47 MACBOOKPRO hass[22938]: TypeError: argument of type 'NoneType' is not iterable
``` one 
whenever I try to run a script `Service not found for call_service at pos 1: (ServiceNotFound(...), 'Service script.turn_on not found')`

**Comment by ludeeus** [comment]
This has nothing to do with this component.
Looks like your script service are missing an entiry_id

**Comment by WagnerBeccard** [comment]
Feels like the other way around - here the full error 
```
ERROR (MainThread) [homeassistant.components.automation] Error while executing automation automation.dashevent_3min. Service not found for call_service at pos 2: (ServiceNotFound(...), 'Service script.turn_on not found')
```
oh yea - and the config checker also refuses to work - at least in the webend 
Did try to down, and upgrade again but still not working.

**Comment by ludeeus** [comment]
You need to  fix your script config before that automation will start to work.

**Comment by ludeeus** [comment]
Did you fix your script issue?

**Comment by WagnerBeccard** [comment]
wtf.. I feel stupid now - Inserted a new line by mistake and it got saved. Didnt had remotly the idea of an config error! Sorry to wasted your time. Thanks for the help!
