### ISSUE TITLE
ModuleNotFoundError: No module named 'pyupdate.ha_custom.custom_cards

### ISSUE THREAD

**Issue by danielwelch** [custom-components/custom_updater#109]
## Version of the custom_component
custom_updater 4.2.15

## Describe the bug
Since updating to 0.88 I have had the following error on startup: 

`ModuleNotFoundError: No module named 'pyupdate.ha_custom.custom_cards'`

See debug output below for full logs.

What I've tried so far:
- searching for previously closed errors, saw suggestions to restart home assistant (done many times but problem persists)
- Removed `deps/python/lib/python3.6`
- Manually downloaded 4.2.15 (was running 4.2.13) but problem persists with newest version.

## `custom_updater` configuration

```yaml

custom_updater:
  track:
    - cards
    - components
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/nervetattoo/simple-thermostat/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json

```

## Resources in lovelace configuration

```yaml

resources:
  - type: module
    url: /local/simple-thermostat/simple-thermostat.js?v=0.17.0
  - type: js
    url: /local/tracker-card/tracker-card.js?v=1.1.0
  - type: module
    url: /local/mini-graph-card/mini-graph-card-bundle.js?v=0.3.0
  - type: module
    url: /local/weather-card/weather-card.js

```

## Tracker-card configuration

```yaml

      - title: null
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker
        type: 'custom:tracker-card'

```

## Debug log

```text

2019-02-27 22:19:54 INFO (MainThread) [custom_components.custom_updater] if you have ANY issues with this, please report them here: https://github.com/custom-components/custom_updater
2019-02-27 22:19:54 DEBUG (MainThread) [custom_components.custom_updater] Version 4.2.15
2019-02-27 22:19:54 DEBUG (MainThread) [custom_components.custom_updater] Mode yaml
2019-02-27 22:19:54 DEBUG (MainThread) [custom_components.custom_updater] CustomCards - __init__
2019-02-27 22:19:54 ERROR (MainThread) [homeassistant.setup] Error during setup of component custom_updater
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/setup.py", line 151, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/custom_updater.py", line 79, in async_setup
    hass, conf_hide_sensor, conf_card_urls, conf_mode)
  File "/config/custom_components/custom_updater.py", line 148, in __init__
    from pyupdate.ha_custom.custom_cards import CustomCards as Cards
ModuleNotFoundError: No module named 'pyupdate.ha_custom.custom_cards'

```

**Comment by danielwelch** [comment]
Never mind, I fixed this by removing the entire `deps/lib/python3.7` directory followed by 2 restarts of Home Assistant. Sorry and thanks for all your excellent work!
