### ISSUE TITLE
Error when installing component

### ISSUE THREAD

**Issue by Btje1977** [custom-components/custom_updater#121]
## Version of the custom_component
Latest

## Describe the bug
Error after adding the updater line to configuration.yaml.

# Add configuration here

custom_updater:

Add your logs here.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 151, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/custom_updater.py", line 80, in async_setup
    hass, conf_hide_sensor, conf_card_urls, conf_mode)
  File "/config/custom_components/custom_updater.py", line 149, in __init__
    from pyupdate.ha_custom.custom_cards import CustomCards as Cards
ModuleNotFoundError: No module named 'pyupdate'
2019-03-09 16:41:46 WARNING (MainThread) [homeassistant.components.sensor.template] Could not render template NextAppointment, the state is unknown.

**Comment by ludeeus** [comment]
Restart homeassistant.
