### ISSUE TITLE
Not able to connect to github repo

### ISSUE THREAD

**Issue by DieterChmod** [custom-components/custom_updater#124]
## Version of the custom_component
4.2.17

## Describe the bug
Custom updater simply doesn't work on homeassistant versions 0.86.X and .89.1.
I wanted to use the custom tracker card together with the custom updater. I followed the instructions for both, the updater component and the tracker card. Unfortunately, the custom updater cannot connect to the remote github repository. Believe me, there is no issue with my internet connection.

```
PermissionError: [Errno 13] Permission denied: '/home/homeassistant/.homeassistant/www/github'
```

## `custom_updater` configuration
In configuration.yaml:
```
custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json
```

## Resources in lovelace configuration
```
resources:
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
```

## Tracker-card configuration
In ui-lovelace.yaml
```
  - title: System
    cards:
      - type: custom:tracker-card
```

## Debug log

```
2019-03-13 08:10:03 INFO (MainThread) [custom_components.custom_updater] if you have ANY issues with this, please report them here: https://github.com/custom-components/custom_updater
2019-03-13 08:10:03 DEBUG (MainThread) [custom_components.custom_updater] Version 4.2.17
2019-03-13 08:10:03 DEBUG (MainThread) [custom_components.custom_updater] Mode yaml
2019-03-13 08:10:03 DEBUG (MainThread) [custom_components.custom_updater] CustomCards - __init__
2019-03-13 08:10:03 DEBUG (MainThread) [custom_components.custom_updater] CustomComponents - __init__
```
...
```
2019-03-13 08:10:22 DEBUG (MainThread) [custom_components.custom_updater] CustomCards - extra_init
2019-03-13 08:10:22 DEBUG (MainThread) [pyupdate.log] CustomCards(init_local_data) - Started
2019-03-13 08:10:22 DEBUG (MainThread) [pyupdate.log] CustomCards(localcards) - Started
2019-03-13 08:10:22 DEBUG (MainThread) [pyupdate.log] CustomCards(localcards) - Getting local cards with mode: yaml
2019-03-13 08:10:22 DEBUG (MainThread) [pyupdate.log] CustomCards(get_info_all_cards) - Started
2019-03-13 08:10:22 DEBUG (MainThread) [pyupdate.log] Common(get_repo_data) - ['https://raw.githubusercontent.com/custom-cards/information/master/repos.json', 'https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json']
2019-03-13 08:10:23 DEBUG (MainThread) [pyupdate.log] CustomCards(get_info_all_cards) - Updated stored data {'count': 58, 'cards': dict_keys(['aftership-card', 'rmv-card', 'plan-coordinates', 'gap-card', 'fold-entity-row', 'useful-markdown-card', 'flex-table-card', 'button-card', 'layout-card', 'boilerplate-card', 'time-input-row', 'upcoming-media-card', 'slider-entity-row', 'spotify-card', 'krisinfo-card', 'toggle-lock-entity-row', 'homeassistant-gen', 'tracker-card', 'card-modder', 'player', 'long-press', 'group-card', 'surveillance-card', 'home-setter', 'list-card', 'monster-card', 'state-switch', 'ext-weblink', 'text-element', 'button-entity-row', 'color-glance-card', 'roku-card', 'config-template-card', 'fullykiosk', 'column-card', 'gauge-card', 'popup-card', 'username-element', 'state-element', 'alarm_control_panel-card', 'browser-commander', 'pc-card', 'thermostat-card', 'beer-card', 'state-attribute-element', 'bignumber-card', 'beer-wishlist-card', 'card-tools', 'card-loader', 'color-picker', 'entity-attributes-card', 'calendar-card', 'auto-entities', 'light-entity-row', 'vertical-stack-in-card', 'compact-custom-header', 'canvas-gauge-card', 'circle-sensor-card'])}
2019-03-13 08:10:23 DEBUG (MainThread) [pyupdate.log] CustomCards(yaml_resources) - Started
2019-03-13 08:10:24 DEBUG (MainThread) [pyupdate.log] CustomCards(yaml_resources) - [OrderedDict([('url', '/customcards/github/custom-cards/tracker-card.js?track=true'), ('type', 'module')])]
2019-03-13 08:10:24 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/homeassistant/.homeassistant/custom_components/custom_updater.py", line 158, in extra_init
    await self.pyupdate.init_local_data()
  File "/srv/homeassistant/lib/python3.5/site-packages/pyupdate/ha_custom/custom_cards.py", line 100, in init_local_data
    await self.localcards()
  File "/srv/homeassistant/lib/python3.5/site-packages/pyupdate/ha_custom/custom_cards.py", line 407, in localcards
    os.makedirs(card_dir, exist_ok=True)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/homeassistant/.homeassistant/www/github'
```
...
```
2019-03-13 08:10:24 DEBUG (MainThread) [pyupdate.log] CustomComponents(get_local_version) - Started for /home/homeassistant/.homeassistant/custom_components/hassbian_config.py
2019-03-13 08:10:24 DEBUG (MainThread) [pyupdate.log] CustomComponents(get_local_version) - 
2019-03-13 08:10:24 DEBUG (MainThread) [pyupdate.log] CustomComponents(get_local_version) - Started for /home/homeassistant/.homeassistant/custom_components/hue/sensor.py
2019-03-13 08:10:24 DEBUG (MainThread) [pyupdate.log] CustomComponents(get_local_version) - 
2019-03-13 08:10:24 DEBUG (MainThread) [pyupdate.log] CustomComponents(get_local_version) - Started for /home/homeassistant/.homeassistant/custom_components/untappd/sensor.py
2019-03-13 08:10:24 DEBUG (MainThread) [pyupdate.log] CustomComponents(get_local_version) - 
2019-03-13 08:10:24 DEBUG (MainThread) [pyupdate.log] CustomComponents(get_local_version) - Started for /home/homeassistant/.homeassistant/custom_components/youtube/sensor.py
2019-03-13 08:10:24 DEBUG (MainThread) [pyupdate.log] CustomComponents(get_local_version) - 
2019-03-13 08:10:24 DEBUG (MainThread) [pyupdate.log] CustomComponents(get_local_version) - Started for /home/homeassistant/.homeassistant/custom_components/sickchill/__init__.py
2019-03-13 08:10:24 DEBUG (MainThread) [pyupdate.log] CustomComponents(get_local_version) - 
2019-03-13 08:10:24 DEBUG (MainThread) [pyupdate.log] CustomComponents(get_local_version) - Started for /home/homeassistant/.homeassistant/custom_components/krisinformation/sensor.py
2019-03-13 08:10:24 DEBUG (MainThread) [pyupdate.log] CustomComponents(get_local_version) - 
2019-03-13 08:10:24 DEBUG (MainThread) [pyupdate.log] CustomComponents(get_local_version) - Started for /home/homeassistant/.homeassistant/custom_components/custom_updater.py
2019-03-13 08:10:24 DEBUG (MainThread) [pyupdate.log] CustomComponents(get_local_version) - module 'custom_components.custom_updater' has no attribute '__version__'
```

**Comment by ludeeus** [comment]
Make sure that the user running HA have write access to www and all subdirs.

**Comment by DieterChmod** [comment]
Thanks. That fixes the permission error. Maybe this information could be added to the installation Wiki to prevent others to fall into the trap too.

However, there is still something fishy. The tracker card isn't shown.

![tracker_card](https://user-images.githubusercontent.com/45570637/54274242-dc463180-4587-11e9-88af-4e8d59863555.jpg)

**Comment by ludeeus** [comment]
does the file exist?

**Comment by DieterChmod** [comment]
Apologies. It's working. Thanks a lot. :) 👍
