### ISSUE TITLE
after 0.78.2 and 0.78.3  update, my  lovelace custom updater is broken

### ISSUE THREAD

**Issue by vMeph** [custom-components/custom_updater#26]
**Version of the custom_component**
version_= '2.7.0'

**Describe the bug**
custom updater is not showing cards and components,after HA 0.78.2 and 0.78.3  update.

**log**

```
2018-09-22 13:21:00 ERROR (MainThread) [homeassistant.setup] Error during setup of component custom_updater
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/custom_updater.py", line 74, in setup
    config_show_installabe)
  File "/config/custom_components/custom_updater.py", line 143, in __init__
    self.cache_versions()
  File "/config/custom_components/custom_updater.py", line 170, in cache_versions
    local_version = self.get_local_version(card[0])
  File "/config/custom_components/custom_updater.py", line 394, in get_local_version
    resources = self.get_resources()
  File "/config/custom_components/custom_updater.py", line 381, in get_resources
    content = yaml.safe_load(local)
  File "/usr/local/lib/python3.6/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 41, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/util/yaml.py", line 205, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 141, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/util/yaml.py", line 232, in _construct_seq
    obj, = loader.construct_yaml_seq(node)
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 393, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 116, in construct_sequence
    for child in node.value]
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 116, in <listcomp>
    for child in node.value]
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/util/yaml.py", line 205, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 141, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
```

**Comment by ludeeus** [comment]
How are your component config?

**Comment by vMeph** [comment]
everything was working fine, until i upgrade the HA so all configs still the same has before, unless by mistake any typo was introduced!!!
not sure if the new version custom_component 2.7.0 add anything to do with it also

on configuration.yaml
```
custom_updater:
```
on lovelcace:
```
- type: custom:tracker-card
            title:
            trackers:
              - sensor.custom_card_tracker
              - sensor.custom_component_tracker
```

**Comment by ludeeus** [comment]
Can you share the `recources` part of your `ui-lovelace.yaml` file?
That is the one it has issues with.
I think this are an issue after 2.6.1 og the component and not HA.

**Comment by vMeph** [comment]
im using thomasloven lovelace-gen, but everything always work fine like it is

```
resources:
  - url: !resource custom_cards/tracker-card/tracker-card.js?v=0.1.4
    type: js
  - url: !resource custom_cards/vertical-stack-in-card/vertical-stack-in-card.js?v=0.0.6
    type: js
  - url: !resource custom_cards/text-element/text-element.js?v=0.0.2
    type: js
  - url: !resource custom_cards/state-element/state-element.js?v=0.0.1
    type: js
  - url: !resource custom_cards/state-attribute-element/state-attribute-element.js?v=0.0.4
    type: js
  - url: !resource custom_cards/circle-sensor-card/circle-sensor-card.js?v=1.2.0
    type: module
  - url: !resource custom_cards/kiosk/kiosk.js?v=22
    type: js
  - url: !resource custom_cards/ext-weblink/ext-weblink.js?v=0.3.2
    type: js
  - url: !resource custom_cards/useful-markdown-card/useful-markdown-card.js?v=54a046
    type: js
  - url: !resource custom_cards/aftership-card/aftership-card.js?v=0.0.2
    type: js
  - url: !resource custom_cards/username-element/username-element.js?v=0.0.1
    type: js
  - url: !resource custom_cards/column-card/column-card.js?v=7221e1
    type: js


  - url: !resource custom_cards/mini-media-player/mini-media-player.js?v=1
    type: js
  - url: !resource custom_cards/light-card/light-card.js?v=1
    type: js
  - url: !resource custom_cards/button-card/button-card.js?v=0.0.2
    type: module
  - url: !resource custom_cards/surveillance-card/surveillance-card.js?v=0.0.1
    type: js
  - url: !resource custom_cards/long-press/long-press.js?v=252428
    type: js
  - url: !resource custom_cards/card-modder/card-modder.js?v=be361f
    type: js
  - url: !resource ciotlosm_cards/group-card/group-card.js?v=0.0.2
    type: js
  - url: !resource ciotlosm_cards/thermostat-card/thermostat-card.js?v=0.1.1
    type: module
  - url: !resource ciotlosm_cards/beer-card/beer-card.js?v=0.2.3
    type: js
  - url: !resource ciotlosm_cards/plan-coordinates/plan-coordinates.js?v=0.1.0
    type: js
  - url: !resource ciotlosm_cards/gauge-card/gauge-card.js?v=0.2.0
    type: js
  - url: !resource ciotlosm_cards/monster-card/monster-card.js?v=0.2.3
    type: js
  - url: !resource ciotlosm_cards/bignumber-card/bignumber-card.js?v=0.0.1
    type: js
  - url: !resource ciotlosm_cards/entity-attributes-card/entity-attributes-card.js?v=0.1.1
    type: js
  - url: !resource ciotlosm_cards/alarm_control_panel-card/alarm_control_panel-card.js?v=0.4.0
    type: js
  - url: !resource ciotlosm_cards/home-setter/home-setter.js?v=0.0.1
    type: js
  - url: https://fonts.googleapis.com/css?family=Clicker+Script|Nunito+Sans|Quattrocento+Sans|Gothic+A1|Inconsolata:700
    type: css
```

**Comment by vMeph** [comment]
@ludeeus i reverted back to version version 2.6.1 and the problem still there
and when putting version 2.5.0  bang it went back to normal, everything working normal
so im guessing the problem is in the last 2 versions

**Comment by ludeeus** [comment]
correct
"I think this are an issue after 2.6.1 og the component and not HA."

**Comment by ludeeus** [comment]
I tried your config, but HA does not allow !resource there... are you sure this is from `ui-lovelace.yaml`?

**Comment by vMeph** [comment]
I use Thomas love Lovelace-Gen
https://github.com/thomasloven/homeassistant-lovelace-gen
my resources are set in a main. yaml

**Comment by ludeeus** [comment]
With 2.7.1 it should finish startup but will probably fail gathering cards

**Comment by rpitera** [comment]
@vMeph - Never heard of this script until just now.  While it looks cool, bear in mind that it's been stated that Lovelace will deprecate !include statements in the near future as they will be making a UI for managing it.  Just something to consider.  I don't know if !resource statements will also be affected but I'd keep an eye out.

**Comment by shreram** [comment]
I ran into the same issue. I am running HA 0.78.3 version. This component worked in the prior release.

I am using the following version of tracker-card.

```
resources:
  - url: /local/tracker-card.js?v=0.1.4
    type: js

```
When I click 'Check' button on the following GUI then I get following error message in the log file. This message gets repeated for at least 10 times.

`2018-09-26 15:13:33 ERROR (MainThread) [frontend.js.latest.201809160] http://192.168.86.226:8123/frontend_latest/app-d4eea1e0.js:434:176 Uncaught TypeError: Cannot read property '_stateDisplay' of null`

![image](https://user-images.githubusercontent.com/16169720/46106388-21bf9f80-c19e-11e8-82a1-98d859be5577.png)

**Comment by shreram** [comment]
**Update:**

After researching further following snippet (!secret) in the ui-lovelace.yaml caused this issue. After I replaced that with the actual URL and restarted HA then I got all the information correctly. I have no idea why that caused an error with custom_updater.  

Here is the error message in the log file regarding !secret.

```
2018-09-26 15:58:04 ERROR (MainThread) [homeassistant.setup] Error during setup of component custom_updater
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/custom_updater.py", line 74, in setup
    config_show_installabe)
  File "/config/custom_components/custom_updater.py", line 143, in __init__
    self.cache_versions()
  File "/config/custom_components/custom_updater.py", line 170, in cache_versions
    local_version = self.get_local_version(card[0])
  File "/config/custom_components/custom_updater.py", line 396, in get_local_version
    resources = self.get_resources()
  File "/config/custom_components/custom_updater.py", line 382, in get_resources
    content = yaml.load(local)
  File "/usr/local/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!secret'
  in "/config/ui-lovelace.yaml", line 410, column 14
```

```
  - title: Weather Maps
    icon: mdi:radar
    cards:
      - type: iframe
        url: !secret darksky_url
        aspect_ratio: 75%
        title: Darksky weather
```

After I corrected the URL then this card worked fine. 

![image](https://user-images.githubusercontent.com/16169720/46108080-c217c300-c1a2-11e8-9b45-8fe032cb9c1d.png)

**Comment by rpitera** [comment]
@vMeph - I noticed this in your posted configs:

```
- url: https://fonts.googleapis.com/css?family=Clicker+Script|Nunito+Sans|Quattrocento+Sans|Gothic+A1|Inconsolata:700
    type: css
```
Are you using this to somehow override the default fonts?  If so, could you explain how?  Been looking ot do this but couldn't find an answer.

**Comment by ludeeus** [comment]
Version 3.0.0 fixes these issues
