### ISSUE TITLE
 Error during setup of component custom_updater (no_lovelace)

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-components/custom_updater#27]
**Version of the custom_component**

'2.7.1'
**Describe the bug**
after having updated to the latest version '2.7.1' on Hassio 0.75.3 (no Lovelace) this is in the log:
anything I can do to correctly install?
**log**

```
018-09-27 07:24:58 ERROR (MainThread) [homeassistant.setup] Error during setup of component custom_updater
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/custom_updater.py", line 73, in setup
    config_show_installabe)
  File "/config/custom_components/custom_updater.py", line 142, in __init__
    self.cache_versions()
  File "/config/custom_components/custom_updater.py", line 169, in cache_versions
    local_version = self.get_local_version(card[0])
  File "/config/custom_components/custom_updater.py", line 395, in get_local_version
    resources = self.get_resources()
  File "/config/custom_components/custom_updater.py", line 382, in get_resources
    if content['resources'] is not None:
KeyError: 'resources'
```

tried 2.7.0 but is almost identical:

```
2018-09-27 09:01:45 ERROR (MainThread) [homeassistant.setup] Error during setup of component custom_updater
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/custom_updater.py", line 73, in setup
    config_show_installabe)
  File "/config/custom_components/custom_updater.py", line 142, in __init__
    self.cache_versions()
  File "/config/custom_components/custom_updater.py", line 169, in cache_versions
    local_version = self.get_local_version(card[0])
  File "/config/custom_components/custom_updater.py", line 393, in get_local_version
    resources = self.get_resources()
  File "/config/custom_components/custom_updater.py", line 381, in get_resources
    if content['resources'] is not None:
KeyError: 'resources'
```

**Comment by ludeeus** [comment]
Not much changed in those between those two versions regarding that.
I'm having issues with replicating this, how are your configuration for this component?

**Comment by hvbhome** [comment]
i have this in configuration.yaml:

```
custom_updater:
  component_urls:
    - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
#  card_urls:
  show_installable: True
```

and show these 2 sensors in a group (but they wont show now because of the error)

      - sensor.custom_component_tracker
      - sensor.custom_card_tracker

**Comment by ludeeus** [comment]
The latest version 3.0.0 does not setup card tracker if you do not have it, so this issue should now be gone.
