### ISSUE TITLE
New has_update attribute breaks custom_updater.update_all service

### ISSUE THREAD

**Issue by pnbruckner** [custom-components/custom_updater#31]
**Version of the custom_component**
2.7.2

**Describe the bug**
Calling custom_updater.update_all service results in exception.

**log**

```
Log Details (ERROR)
Fri Sep 28 2018 08:03:32 GMT-0500 (Central Daylight Time)

Error executing service <ServiceCall custom_updater.update_all (c:834ef85f68774375912c7a637197e778)>
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1125, in _event_to_service_call
    await self._hass.async_add_executor_job(execute_service)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1122, in execute_service
    service_handler.func(service_call)
  File "/home/homeassistant/.homeassistant/custom_components/custom_updater.py", line 96, in update_all_service
    components_controller.update_all()
  File "/home/homeassistant/.homeassistant/custom_components/custom_updater.py", line 468, in update_all
    if (self.hass.data[COMP_DATA][name]['has_update'] and
TypeError: list indices must be integers or slices, not str
```
**Additional information**
After adding some extra debugging statements I saw that name was 'has_update'. I think line 466 needs to change to:
```
if name not in ('domain', 'repo', 'hidden', 'has_update'):
```
I made this change in my local copy and it fixed the problem.

**Comment by ludeeus** [comment]
Thanks for this, I forgot that :/
Since you have the solution why not a PR with it?

**Comment by rpitera** [comment]
What exactly is the function of 'has_update'?  It's showing up on my tracker card as if it was a tracked entity and has n/a for the values.  Is it supposed to or is this an issue with the tracker card not being updated to support this new attribute?  (FYI: I did the change suggested above before restarting and taking this screenshot.)

![clipboard01](https://user-images.githubusercontent.com/19910294/46223719-1c8b5d80-c322-11e8-89a5-a2c18ab7e09f.png)

**Comment by pnbruckner** [comment]
>Since you have the solution why not a PR with it?

I can do that.
