### ISSUE TITLE
custom_updater.install broken if not all track options are used

### ISSUE THREAD

**Issue by pnbruckner** [custom-components/custom_updater#39]
**Version of the custom_component**
3.1.1

**Describe the bug**
Using custom_updater.install service causes an exception if not all track options are used. E.g., I'm using just components and python_scripts.

**log**

```
Log Details (ERROR)
Mon Oct 01 2018 16:33:53 GMT-0500 (Central Daylight Time)

Error executing service <ServiceCall custom_updater.install (c:d9fc1b25293d475285ad9a2061cea5bd): element=light_store>
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1125, in _event_to_service_call
    await self._hass.async_add_executor_job(execute_service)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1122, in execute_service
    service_handler.func(service_call)
  File "/home/homeassistant/.homeassistant/custom_components/custom_updater.py", line 104, in install_service
    card_controller.install(element)
NameError: free variable 'card_controller' referenced before assignment in enclosing scope```

**Comment by ludeeus** [comment]
Thanks for reporting :)
Have corrected that now in 3.1.2
Fix for install function (#41)
