### ISSUE TITLE
Updating Custom_Updater via its own card is a temporary disappearing act

### ISSUE THREAD

**Issue by GaryOkie** [custom-components/custom_updater#54]
**Version**
3.1.7

**Describe the bug**
Upon updating custom_updater itself via the lovelace card, the code itself  updated fine in the custom_components directory via "Update All", but the code did not continue to  update the remainder of the custom components.   It just quit - custom_updater was no longer listed in the card, and "Update All" or "Check All" did nothing.   

I restarted Hassio (80.1) with custom_updater debugging enabled and found that custom_updater was now listed in the card, and Update All worked (sort of).  It updated  just one custom component, but no others.   It threw the error below.   I need to repeat Check/Update All to update the next component.

This problem has been duplicated on two separate Hassio systems.

**log**

```
2018-10-17 10:13:16 WARNING (MainThread) [homeassistant.loader] You are using a custom component for custom_updater which has not been tested by Home Assistant. This component might cause stability prob
2018-10-17 10:13:16 WARNING (MainThread) [homeassistant.loader] You are using a custom component for device_tracker.life360 which has not been tested by Home Assistant. This component might cause stabil
2018-10-17 10:13:52 INFO (SyncWorker_2) [custom_components.custom_updater] if you have ANY issues with this, please report them here: https://github.com/custom-components/custom_updater
2018-10-17 10:13:59 ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting
2018-10-17 10:14:59 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall custom_updater.update_all (c:ab24d86d0f03422b8556f6fa0f2a15f1)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1185, in _event_to_service_call
    await self._hass.async_add_executor_job(execute_service)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1182, in execute_service
    service_handler.func(service_call)
  File "/config/custom_components/custom_updater.py", line 96, in update_all_service
    components_controller.update_all()
  File "/config/custom_components/custom_updater.py", line 196, in update_all
    self.custom_url)
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_components.py", line 78, in update_all
    upgrade_single(base_dir, name, custom_repos)
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_components.py", line 90, in upgrade_single
    update_requirements(local_file)
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_components.py", line 135, in update_requirements
    for package in requirements.split(' '):
AttributeError: 'list' object has no attribute 'split'
2018-10-17 10:15:27 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall custom_updater.update_all (c:de2d791483c64f2d8d23b0e9f77d993b)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1185, in _event_to_service_call
    await self._hass.async_add_executor_job(execute_service)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1182, in execute_service
    service_handler.func(service_call)
  File "/config/custom_components/custom_updater.py", line 96, in update_all_service
    components_controller.update_all()
  File "/config/custom_components/custom_updater.py", line 196, in update_all
    self.custom_url)
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_components.py", line 78, in update_all
    upgrade_single(base_dir, name, custom_repos)
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_components.py", line 90, in upgrade_single
    update_requirements(local_file)
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_components.py", line 135, in update_requirements
    for package in requirements.split(' '):
AttributeError: 'list' object has no attribute 'split'

```

**Comment by ludeeus** [comment]
Can you add full debug it is `pyupdate` that was usefull logs for this :)
<https://github.com/custom-components/custom_updater/wiki/Debug>

**Comment by GaryOkie** [comment]
oh - sorry I didn't enable debug on pyupdate properly.     I guess I will need to manually edit the custom code to an older version to have it take effect, assuming that's all it keys on.

**Comment by GaryOkie** [comment]
I manually edited the new version of custom_updater.py and a life360 custom component to a fake older version to trigger an update (as I didn't know how to get the original older versions).   That worked, but the problem with custom_updater disappearing was not duplicated, so something in the new version fixed that.    Also, it did not automatically update each component without doing a Check first, which is different behavior than before.  The python errors are the same, indicating a problem somewhere.

I have the debug file but it is quite large due to life360 detail.  I'll try again, this time to disable debug for life360 and pyupdate only.   Are you not able to duplicate these same python errors when updating?

**Comment by GaryOkie** [comment]
After manually changing the __Version__ in 3 custom components to a fake older version, here's the expected update card:
![update](https://user-images.githubusercontent.com/37629938/47120409-312d8800-d234-11e8-8999-6251a1f5a09a.JPG)

- Clicked Update all.   ~5 second delay before service message call popup appeared.   Then nothing changed in the above display.
- Next, clicked "check".   It then showed custom_updater and device_tracker composite were updated, but not device_tracker.life360.
- Clicked Check again.   Nothing changed.
- Clicked Update all.   after service call message appeared, no apparent change - device_tracker.life360 still showed a red 1.6.0.   
- Click Check again.   Now all show updated.    Exiting hassio and grabbing logs  (which are quite verbose still)...

Home_Assistant.log:
`
[home-assistant.log](https://github.com/custom-components/custom_updater/files/2489581/home-assistant.log)
`

**Comment by pnbruckner** [comment]
I experienced a similar error. The problem seems to be in [this code](https://github.com/ludeeus/pyupdate/blob/1d57fc82bea87b25e9bd7001c7e6f7f8f5c8b954/pyupdate/ha_custom/custom_components.py#L118-L137) in pyupdate. Assuming you only want to be able to handle a single REQUIREMENTS line, then you can fix it by changing line 120 to `requirements = None`.

**Comment by GaryOkie** [comment]
Nice catch [Phil] - thanks!

**Comment by ludeeus** [comment]
So that was embarrassing, I only tested that feature if there were requirements... 🤦‍♂️ 
Should be corrected now.
Thanks, @pnbruckner !
