### ISSUE TITLE
No module named 'pyupdate'

### ISSUE THREAD

**Issue by TheZoker** [custom-components/custom_updater#58]
**Version of the custom_component**
3.1.8

**Describe the bug**
On restart, I get this log:
```
Error during setup of component custom_updater
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/custom_updater.py", line 71, in setup
    config_show_installabe)
  File "/config/custom_components/custom_updater.py", line 171, in __init__
    from pyupdate.ha_custom import custom_components
ModuleNotFoundError: No module named 'pyupdate'
```

Does it even work with hassio? Or is pyupdate missing there?

**Comment by TheZoker** [comment]
Yes it worked, thank you!
