### ISSUE TITLE
custom_updater install element error

### ISSUE THREAD

**Issue by finity69x2** [custom-components/custom_updater#61]
**Version of the custom_component**

3.1.0
**Describe the bug**
trying to install a custom component (life360).

here is my configuration.yaml section:

```
custom_updater:
  show_installable: True
  hide_sensor: true
  track:
    - components
    - python_scripts
  component_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  python_script_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/python_scripts.json
```

**log**

```
2018-11-26 17:10:04 DEBUG (SyncWorker_12) [custom_components.custom_updater] Installing life360
2018-11-26 17:10:04 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall custom_updater.install (c:fe377ee939144431a0ed7512bb19af39): element=life360>
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/core.py", line 1185, in _event_to_service_call
    await self._hass.async_add_executor_job(execute_service)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/core.py", line 1182, in execute_service
    service_handler.func(service_call)
  File "/config/custom_components/custom_updater.py", line 104, in install_service
    card_controller.install(element)
NameError: free variable 'card_controller' referenced before assignment in enclosing scope
```

**Comment by finity69x2** [comment]
Never mind. I was on an older version and this issue is fixed in the newer version.
