### ISSUE TITLE
Error during setup of component custom_updater

### ISSUE THREAD

**Issue by GaryOkie** [custom-components/custom_updater#67]
**VERSION = '3.1.8'**

**Describe the bug**
Error during setup of component custom_updater (json error - missing delimeter).   Also commented out component_urls option and got the same error.   I  did ensure code was pasted from RAW text from Github and was not formatted text.

Not sure when it last worked, but it used to work well.    

**configuration.yaml**
```
custom_updater:
  component_urls: https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json

lovelace:
  yaml
```

**ui-lovelace.yaml**
```
resources:
  - url: /local/tracker-card.js?v=0
    type: js
  - type: custom:tracker-card
    title:
    trackers:
      - sensor.custom_card_tracker
      - sensor.custom_component_tracker
```
**log**

```
Home Assistant
0.84.6

Error during setup of component custom_updater
12:21 PM deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_components.py (ERROR)
You are using a custom component for device_tracker.composite which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
12:21 PM loader.py (WARNING)
You are using a custom component for device_tracker.asuswrt which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
12:21 PM loader.py (WARNING)
You are using a custom component for device_tracker.life360 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
12:21 PM loader.py (WARNING)
You are using a custom component for custom_updater which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
12:21 PM loader.py (WARNING)
 

Log Details (ERROR)
Fri Jan 04 2019 12:21:06 GMT-0600 (Central Standard Time)

Error during setup of component custom_updater
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/custom_updater.py", line 71, in setup
    config_show_installabe)
  File "/config/custom_components/custom_updater.py", line 180, in __init__
    self.cache_versions()
  File "/config/custom_components/custom_updater.py", line 186, in cache_versions
    self.custom_url)
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_components.py", line 41, in get_sensor_data
    components = get_info_all_components(custom_repos)
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_components.py", line 19, in get_info_all_components
    for name, component in response.json().items():
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting ',' delimiter or '}': line 188 column 146 (char 11239)
```

**Comment by tjorim** [comment]
Same here, looks to be related to the custom_components repo.
@ludeeus Here's the commit https://github.com/custom-components/information/commit/d7646153f7d4fd40cbf8d6d677e3ed6d8d6aa26e causing it.
As you can see, the line number matches.

**Comment by dvbit** [comment]
ditto

**Comment by GaryOkie** [comment]
Nice spot @tjorim !   I can easily see the missing "}" in the code.

So this is another risk to custom components I wasn't aware of...  background updates to dependencies.

**Comment by ludeeus** [comment]
Should be ok now

**Comment by GaryOkie** [comment]
Yeah, it's working fine again now.  Thanks.    

still, a bit uncomfortable about the exposure to these types of background updates.

**Comment by ludeeus** [comment]
It fetches new information (All components in HA does that....)
It does not update anything unless you make it update.
