### ISSUE TITLE
Updates not compatible with lastest lovelace_gen

### ISSUE THREAD

**Issue by bratanon** [custom-components/custom_updater#74]
**Version of the custom_component**
If this is custom_updater version it is 3.1.8.

**Describe the bug**
When performing an update, `get_card_dir` will look for the string `!resource` in the main.yaml file if lovelace-gen is used. 

In the latest release of lovelave_gen.py that special directive is gone so users can't use that anymore.

**log**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/websocket_api/decorators.py", line 17, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/websocket_api/commands.py", line 148, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1129, in async_call
    self._execute_service(handler, service_call))
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1153, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/custom_updater.py", line 94, in update_all_service
    card_controller.update_all()
  File "/config/custom_components/custom_updater.py", line 149, in update_all
    self.custom_url)
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_cards.py", line 87, in update_all
    upgrade_single(base_dir, name, custom_repos)
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_cards.py", line 97, in upgrade_single
    local_file = get_card_dir(base_dir, name) + name + '.js'
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_cards.py", line 135, in get_card_dir
    card = line.split('!resource ')[1].split(name + '.js')
IndexError: list index out of range
```

**Comment by bratanon** [comment]
This is actually not an issue with custom_updater, it seems to be an issue for the pyupdate lib.

I addad this issue to thier repo aswell.
https://github.com/ludeeus/pyupdate/issues/3

**Comment by ludeeus** [comment]
closing in favor of ludeeus/pyupdate#3
