### ISSUE TITLE
problem with pyupdate

### ISSUE THREAD

**Issue by frajoc** [custom-components/custom_updater#76]
HA 0.87.0

Unable to install pyupdate, causing that the card/cards dont show on lovelace in the tracker trace.

2019-02-07 14:47:17 WARNING (MainThread) [homeassistant.loader] You are using a custom component for custom_updater which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-02-07 14:47:57 ERROR (SyncWorker_0) [homeassistant.util.package] Unable to install package pyupdate==0.2.20: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe2cfd909b0>: Failed to establish a new connection: [Errno -3] Try again',)': /simple/pyupdate/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe2cfd90748>: Failed to establish a new connection: [Errno -3] Try again',)': /simple/pyupdate/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe2cfd90630>: Failed to establish a new connection: [Errno -3] Try again',)': /simple/pyupdate/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe2cfd90518>: Failed to establish a new connection: [Errno -3] Try again',)': /simple/pyupdate/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe2cfd90278>: Failed to establish a new connection: [Errno -3] Try again',)': /simple/pyupdate/
  Could not find a version that satisfies the requirement pyupdate==0.2.20 (from versions: )
No matching distribution found for pyupdate==0.2.20
2019-02-07 14:47:57 ERROR (MainThread) [homeassistant.requirements] Not initializing custom_updater because could not install requirement pyupdate==0.2.20
2019-02-07 14:47:57 ERROR (MainThread) [homeassistant.setup] Setup failed for custom_updater: Could not install all requirements.

**Comment by ludeeus** [comment]
It looks like you have a internet/DNS issue

**Comment by frajoc** [comment]
ahhh, it was my VPN blocking.
now its disable and get this error instead
2019-02-07 18:32:06 WARNING (MainThread) [homeassistant.loader] You are using a custom component for custom_updater which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-02-07 18:32:11 ERROR (MainThread) [homeassistant.setup] Error during setup of component custom_updater
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/custom_updater.py", line 65, in setup
    config_show_installabe)
  File "/config/custom_components/custom_updater.py", line 125, in __init__
    from pyupdate.ha_custom import custom_cards
ModuleNotFoundError: No module named 'pyupdate'

**Comment by frajoc** [comment]
Thanks.
It was my VPN that was blocking. After disable i have no fails anymore.
But still i cant see my card or components in the lovelace

**Comment by frajoc** [comment]
Thanks,
It was my VPN blocking :)
Now i need to find out how i can run it at the same time as my VPN is active
