### ISSUE TITLE
Docs wrong for mode?

### ISSUE THREAD

**Issue by DavidFW1960** [custom-components/custom_updater#78]
**Version of the custom_component**

4 - latest
**Describe the bug**
The docs say the mode is a list?
```
  mode: 
    - yaml
**log**
<!-- issues without debug logging will be closed-->
```
Invalid config for [custom_updater]: value should be a string for dictionary value @ data['custom_updater']['mode']. Got ['yaml']. (See /config/configuration.yaml, line 344). Please check the docs at https://home-assistant.io/components/custom_updater/
Add your logs here.
```
Using 
```
  mode: yaml
```
validates.

I know that yaml is the default but I might switch to storage.

**Comment by DavidFW1960** [comment]
also after restarting I get this:
```
Thu Feb 14 2019 11:19:20 GMT+1100 (Australian Eastern Daylight Time)
Error during setup of component custom_updater
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/custom_updater.py", line 70, in setup
    config_show_installabe, conf_mode)
  File "/config/custom_components/custom_updater.py", line 141, in __init__
    self.ha_conf_dir, self.mode, conf_card_urls)
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_cards.py", line 74, in init_local_data
    local_cards = localcards(base_dir, mode)
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_cards.py", line 266, in localcards
    for entry in yaml_resources(base_dir):
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_cards.py", line 252, in yaml_resources
    load = yaml.load(localfile, Loader)
  File "/usr/local/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.6/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib/python3.6/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.6/site-packages/yaml/scanner.py", line 257, in fetch_more_tokens
    self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "/config/ui-lovelace.yaml", line 196, column 31
```

**Comment by DavidFW1960** [comment]
I just saw the release notes... This didn't seem to be linked on the card page
