### ISSUE TITLE
Error message with new 0.88.0b0 of home assistant

### ISSUE THREAD

**Issue by Obicom** [custom-components/custom_updater#82]
**Version of the custom_component**

**Describe the bug**
The custom component custom_updater lead in a error with new ha version 0.88.0.
(architecture change of custom components) See new release note: https://rc--home-assistant-docs.netlify.com/blog/2019/02/13/release-88/

**log**

> 2019-02-14 22:46:30 ERROR (MainThread) [homeassistant.setup] Error during setup of component custom_updater
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 154, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/custom_updater.py", line 65, in setup
    config_show_installabe)
  File "/config/custom_components/custom_updater.py", line 125, in __init__
    from pyupdate.ha_custom import custom_cards
ModuleNotFoundError: No module named 'pyupdate'

**Comment by ludeeus** [comment]
That is normal, restart homeassistant and it should work again

**Comment by ludeeus** [comment]
Since also posted #83 I assume you got this working,
