### ISSUE TITLE
UnicodeDecodeError when loading ui-lovelace.yaml

### ISSUE THREAD

**Issue by kugan49** [custom-components/custom_updater#88]
## Version of the custom_component :
4.1.1 and 4.1.3

## Describe the bug :

custom updater won't start anymore (see log for message).
After some tests, it's in cards tracking the problem maybe reading this file https://raw.githubusercontent.com/custom-cards/information/master/repos.json ? 

## `custom_updater` configuration

```yaml

custom_updater:
  show_installable: false
  hide_sensor: false
  track:
    - components
    - cards
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/ljmerza/calendar-card/master/custom_updater.json
    - https://raw.githubusercontent.com/nervetattoo/simple-thermostat/master/tracker.json


```

## Resources in lovelace configuration

```yaml

resources:
  - url: /local/calendar-card/calendar-card.js?v=2.1.0
    type: js
  - url: /local/lovelace-card-modder/card-modder.js?v=f3d96f
    type: module
  - url: /local/lovelace-card-tools/card-tools.js?v=f5bb8e
    type: js
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=1.0.0b5
    type: module
  - url: /local/custom-lovelace/monster-card/monster-card.js?v=0.2.3
    type: js
  - url: /local/simple-thermostat.min.js?v=1
    type: module 
  - url: /local/tracker-card.js?v=0.3.2
    type: js
  - url: /local/useful-markdown-card.js?v=dfc268
    type: module
  - url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/weather-card.min.js
    type: module

```

## Full lovelace

```yaml

title: Jace
resources:
  - url: /local/tracker-card.js?v=0.3.2
    type: js
  - url: /local/custom-lovelace/monster-card/monster-card.js?v=0.2.3
    type: js
  - url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/weather-card.min.js
    type: module
  - url: /local/lovelace-card-modder/card-modder.js?v=f3d96f
    type: module
  - url: /local/lovelace-card-tools/card-tools.js?v=f5bb8e
    type: js
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=1.0.0b5
    type: module
  - url: /local/calendar-card/calendar-card.js?v=2.1.0
    type: js
  - url: /local/simple-thermostat.min.js?v=1
    type: module 
  - url: /local/useful-markdown-card.js?v=9377d8
    type: module
views:
  - !include lovelace/00_home_view.yaml
  - !include lovelace/10_heat_view.yaml
  - !include lovelace/30_media_view.yaml
  - !include lovelace/80_config_view.yaml
  - !include lovelace/90_links_view.yaml


# Exclude entities from "Unused entities" view
excluded_entities:
  - alert.gateway_off


```

## Tracker-card configuration

```yaml

 card:  
      type: custom:tracker-card
      title: "Version Composants"
      name_text: "Nom"
      current_text: "Actuelle"
      available_text: "Disponible"
      check_text: "VERIFIER"
      update_all_text: "MAJ TOTALE"
      trackers:
        - sensor.custom_card_tracker
        - sensor.custom_component_tracker

```

## Debug log

```text

Error during setup of component custom_updater
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/setup.py", line 145, in _async_setup_component
    hass, processed_config)
  File "/home/osmc/config/homeassistant/custom_components/custom_updater.py", line 77, in async_setup
    await card_controller.extra_init()
  File "/home/osmc/config/homeassistant/custom_components/custom_updater.py", line 153, in extra_init
    await self.pyupdate.init_local_data()
  File "/srv/homeassistant/lib/python3.5/site-packages/pyupdate/ha_custom/custom_cards.py", line 92, in init_local_data
    await self.localcards()
  File "/srv/homeassistant/lib/python3.5/site-packages/pyupdate/ha_custom/custom_cards.py", line 350, in localcards
    resources = await self.yaml_resources()
  File "/srv/homeassistant/lib/python3.5/site-packages/pyupdate/ha_custom/custom_cards.py", line 331, in yaml_resources
    load = yaml.load(localfile, Loader)
  File "/srv/homeassistant/lib/python3.5/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/srv/homeassistant/lib/python3.5/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/srv/homeassistant/lib/python3.5/site-packages/yaml/constructor.py", line 41, in construct_document
    data = self.construct_object(node)
  File "/srv/homeassistant/lib/python3.5/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/util/yaml.py", line 205, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/srv/homeassistant/lib/python3.5/site-packages/yaml/constructor.py", line 141, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/srv/homeassistant/lib/python3.5/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/util/yaml.py", line 232, in _construct_seq
    obj, = loader.construct_yaml_seq(node)
  File "/srv/homeassistant/lib/python3.5/site-packages/yaml/constructor.py", line 393, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/srv/homeassistant/lib/python3.5/site-packages/yaml/constructor.py", line 116, in construct_sequence
    for child in node.value]
  File "/srv/homeassistant/lib/python3.5/site-packages/yaml/constructor.py", line 116, in <listcomp>
    for child in node.value]
  File "/srv/homeassistant/lib/python3.5/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/srv/homeassistant/lib/python3.5/site-packages/pyupdate/ha_custom/custom_cards.py", line 34, in construct_include
    return yaml.load(localfile, Loader)
  File "/srv/homeassistant/lib/python3.5/site-packages/yaml/__init__.py", line 70, in load
    loader = Loader(stream)
  File "/srv/homeassistant/lib/python3.5/site-packages/pyupdate/ha_custom/custom_cards.py", line 23, in __init__
    super().__init__(stream)
  File "/srv/homeassistant/lib/python3.5/site-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/srv/homeassistant/lib/python3.5/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/srv/homeassistant/lib/python3.5/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/srv/homeassistant/lib/python3.5/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5192: ordinal not in range(128)

```

**Comment by ludeeus** [comment]
> latest

This is not a version..


The issue here is with reading your ui-loveleace.yaml file, can you paste the entire file here?

**Comment by kugan49** [comment]
Hi, thanks for your time.
I updated my first post.

**Comment by ludeeus** [comment]
Since you are using !include that is not your entire config ;)
Try upgrading to 4.1.4

**Comment by kugan49** [comment]
Thank you again for your time and your informations :

I found the problem :

I had some accented characters in my yaml :

```yaml
#################################################################
#                                                               #
#                    Entités en probleme Card                   #
#                                                               #
#################################################################
 - type: custom:monster-card
    style:                 
      border-radius: 20px
      border: solid 1px rgba(100,100,100,0.3)
      box-shadow: 3px 3px rgba(0,0,0,0.4)
      overflow: hidden
    card:
      type: picture-glance
      title: "Entités en problème"
      image: /local/background/core_network.jpg
    filter:
      include:
        - state: "unknown"
      exclude:
        - entity_id: group.*

```

I'm surprised because homeassistant work well with this but not custom_updater.

I changed with this (also problem in comments) :

```yaml
#                    Entites en probleme Card                   #
      title: "Entit\xE9s en probl\xE8me"

```
 and now all is OK thank you
